// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLdlsLg8wcnwBL47aHPcZEJPYGOyoNuI4',
    appId: '1:650996243996:web:fe4d89a20c494f5de389d9',
    messagingSenderId: '650996243996',
    projectId: 'notesapp-2e479',
    authDomain: 'notesapp-2e479.firebaseapp.com',
    storageBucket: 'notesapp-2e479.firebasestorage.app',
    measurementId: 'G-HB40R6Y4Y7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhRvysxxD-oZJVdjlVsa3rlaCVEUASQjg',
    appId: '1:650996243996:android:10e3ca7277b7cff8e389d9',
    messagingSenderId: '650996243996',
    projectId: 'notesapp-2e479',
    storageBucket: 'notesapp-2e479.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmNf-H8pvLdAvR455aZMOHTeGq5YoGy2I',
    appId: '1:650996243996:ios:645aa5f03b11b554e389d9',
    messagingSenderId: '650996243996',
    projectId: 'notesapp-2e479',
    storageBucket: 'notesapp-2e479.firebasestorage.app',
    iosBundleId: 'com.example.notesApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmNf-H8pvLdAvR455aZMOHTeGq5YoGy2I',
    appId: '1:650996243996:ios:645aa5f03b11b554e389d9',
    messagingSenderId: '650996243996',
    projectId: 'notesapp-2e479',
    storageBucket: 'notesapp-2e479.firebasestorage.app',
    iosBundleId: 'com.example.notesApps',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLdlsLg8wcnwBL47aHPcZEJPYGOyoNuI4',
    appId: '1:650996243996:web:b20b694c29cb6a3ce389d9',
    messagingSenderId: '650996243996',
    projectId: 'notesapp-2e479',
    authDomain: 'notesapp-2e479.firebaseapp.com',
    storageBucket: 'notesapp-2e479.firebasestorage.app',
    measurementId: 'G-RK3W33ZX1X',
  );

}